### ISSUE TITLE
自动更新把 V2Ray-Desktop 旧版本当成新版本推送了

### ISSUE THREAD

**Issue by jat001** [kidonng/sushi#18]
最新的是 2.2.1 3da6b72a76e3e4f0f7cf6bdf1b49dcb0becd56e4 把 2.2.0 替换成了 2.1.1

**Comment by jat001** [comment]
![屏幕截图 2021-02-10 063419](https://user-images.githubusercontent.com/1758850/107437522-18b2ab80-6b6a-11eb-8dfc-1824e34cb251.jpg)
仔细一看，原来是作者把文件名写错了🤣

**Comment by jat001** [comment]
@kidonng 上游已修复，麻烦手动更新下

**Comment by kidonng** [comment]
Does e8fa77ec4bfc27d2426400e489496dfc917b4ae5 fixed this?

**Comment by jat001** [comment]
请删掉 `extract_dir`，压缩文件里没有目录了

**Comment by kidonng** [comment]
Done. Please check again.
