### ISSUE TITLE
fluent-reader 已经在 extras 中

### ISSUE THREAD

**Issue by ChungZH** [kidonng/sushi#2]
https://github.com/lukesampson/scoop-extras/blob/master/bucket/fluent-reader.json

**Comment by kidonng** [comment]
Scoop 没有 deprecate 和 rename 某个应用的方法，直接移除某个应用的 manifest 会导致 `scoop status` 提示其 manifest 不存在。

虽然我在 64a31947c2b5c7bfca9107af56cfc62078cbec61 和 fad0bfefc4fda844c43a66d15a2af60a539df14b （后者在 0addc8aa2fd8b9f389a3a96f952d878148466d70 中恢复了）里进行了此类操作，但是不代表这是被提倡的。Scoop 本身的开发非常缓慢，我正在写一个 wrapper 解决这些问题，到时候再移除吧。

**Comment by kidonng** [comment]
5c2c1adbfa27969bda530c2a3123da970320d702
