### ISSUE TITLE
microsoft-edge-dev@94.0.982.2: Hash check failed

### ISSUE THREAD

**Issue by R0FGV** [kidonng/sushi#37]
Hash check failed!
App:         sushi/microsoft-edge-dev
URL:         https://edge-dl.kidonng.workers.dev/https://api.shuax.com/v2/download/edge/dev/x64#/dl.7z
First bytes: 60 33 68 79 67 84 89 80
Expected:    600ca927634a91d6d1c41a8e4c7de665ff773dddcf7652428025efe1cb5165bf
Actual:      a122353d099bb202ec88bb62f2bc9aaf330fb772af31e4710c7858d4ca1bda75

**Comment by kidonng** [comment]
Seems like the API this bucket died long time ago. I suggest using one in [dorado](https://github.com/chawyehsu/dorado) bucket instead:

```
scoop bucket add dorado https://github.com/chawyehsu/dorado
scoop install dorado/microsoftedge-dev
```
